version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /home/chabad/jellyfin/config:/config
      - /home/chabad/jellyfin/cache:/cache
      - type: bind
        source: /home/chabad/jellyfin/media
        target: /media
        read_only: true
    restart: 'unless-stopped'
